# Generated by Django 5.2.11 on 2026-03-19 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recolteurs', '0001_initial'),
        ('secteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheRecolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('superviseur_general', models.CharField(blank=True, max_length=120)),
                ('bareme_grands', models.PositiveIntegerField(default=60)),
                ('bareme_moyens', models.PositiveIntegerField(default=50)),
                ('bareme_petits', models.PositiveIntegerField(default=25)),
                ('depense_nourriture', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('depense_transport', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FicheRecolteLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recolteur_nom', models.CharField(blank=True, max_length=120)),
                ('regime_type', models.CharField(choices=[('grands', 'Grands'), ('moyens', 'Moyens'), ('petits', 'Petits')], max_length=10)),
                ('paye_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='recoltes.ficherecolte')),
                ('recolteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_recolte', to='recolteurs.recolteur')),
            ],
        ),
        migrations.CreateModel(
            name='FicheRecuVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=120)),
                ('pesee_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('non_conformes_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='recoltes.ficherecolte')),
            ],
        ),
        migrations.CreateModel(
            name='SuperviseurAdjoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('secteur_ou_recolteur', models.CharField(max_length=120)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superviseurs_adjoints', to='recoltes.ficherecolte')),
            ],
        ),
        migrations.CreateModel(
            name='FicheRecolteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur_code', models.CharField(blank=True, max_length=20)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_recolte', to='secteurs.secteur')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='recoltes.ficherecolteligne')),
            ],
            options={
                'unique_together': {('ligne', 'secteur')},
            },
        ),
    ]
