# Generated by Django 5.2.11 on 2026-03-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=120)),
                ('zone', models.CharField(max_length=120)),
                ('niveau', models.CharField(choices=[('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Eleve', 'Eleve')], default='Moyen', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
