# Generated by Django 5.2.11 on 2026-03-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois'), ('quarter', 'Trimestre'), ('semester', 'Semestre'), ('year', 'Annee')], default='month', max_length=20)),
                ('targets', models.JSONField(default=list)),
                ('dimensions', models.JSONField(default=list)),
                ('parameters', models.JSONField(default=dict)),
                ('coefficients', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
