# Generated by Django 5.2.11 on 2026-03-20 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_predictionscenario'),
        ('secteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('frequency', models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois'), ('quarter', 'Trimestre'), ('semester', 'Semestre'), ('year', 'Annee')], default='month', max_length=20)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('workforce_count', models.PositiveIntegerField(blank=True, null=True)),
                ('fertilizer_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('maintenance_index', models.PositiveIntegerField(blank=True, null=True)),
                ('nonconformity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active_area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_ia', to='secteurs.secteur')),
            ],
        ),
    ]
