# Generated by Django 5.2.11 on 2026-03-19 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recolteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recolteurs', to='secteurs.secteur')),
            ],
        ),
    ]
